[project]
name = "muvicell"
version = "0.1.0"
description = "From cell-type stratified features to multicellular coordinated programs"
readme = "README.md"
authors = [
    { name = "HartmannLab", email = "info@hartmannlab.org" }
]
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.20.0,<2.0",
    "pandas>=1.5.0,<3.0",
    "scipy>=1.9.0,<2.0",
    "scikit-learn>=1.1.0,<2.0",
    "matplotlib>=3.5.0,<4.0",
    "seaborn>=0.11.0,<1.0",
    "plotnine>=0.10.0,<1.0",
    "scanpy>=1.9.0,<2.0",
    "anndata>=0.8.0,<0.11.0",
    "muon>=0.1.0,<1.0",
    "jupyter>=1.0.0,<2.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "isort>=5.10.0",
    "flake8>=5.0.0"
]
muvi = [
    "muvi>=0.1.0"
]

[build-system]
requires = ["uv_build>=0.8.18,<0.9.0"]
build-backend = "uv_build"
